apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-skku-login
bases:
- ../../base
- namespace.yaml
patches:
- target:
    kind: Ingress
    name: ingress
  path: domain.json