apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-skku-login
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
bases:
- ../../base
resources:
- namespace.yaml
- secret.yaml