apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
type: Opaque
data:
  DB_USERNAME: <path:kv/data/skku-login#name | base64encode>
  DB_PASSWORD: <path:kv/data/skku-login#major | base64encode>