apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: skku-login
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
resources:
- ../../base
- namespace.yaml
- secret.yaml
images:
- name: sce06147/skku-login
