apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gobongbap
patches:
- path: domain.json
  target:
    kind: Ingress
    name: ingress
resources:
- ../../base
- namespace.yaml
images:
- name: sce06147/gobongbap
  newTag: 9e002bfb213030c2c03464c3c52766861919593e
