apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
type: Opaque
data:
  STUDENT_NAME: <path:kv/data/skku-login#name | base64encode>
  STUDENT_MAJOR: <path:kv/data/skku-login#major | base64encode>