apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - image: sce06147/skku-login
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 9000
        envFrom:
        - secretRef:
            name: vault-secret
